### PR TITLE
Hemalvarambhia issue 48

### LINKED ISSUE #48: Math-Quaternion and Math-QuaternionExtensions should be merge
Like Math-Complex and Math-ComplexExtensions previously.

### PR DESCRIPTION
**Pull request by SergeStinckwich**
Hemal fix #48

### CODE REVIEW

**Comment by hemalvarambhia** [comment]
The QuaternionExtensions package has not been deleted from the file system yet. Initially, I unloaded the said package from Pharo and the tests still passed. This would indicate that we can safely delete it.

**Comment by SergeStinckwich** [comment]
You have to modify the BaselineOfPolyMath that load the packages.

**Comment by hemalvarambhia** [comment]
Presumeably I just remove L60 of that file: https://github.com/PolyMathOrg/PolyMath/blob/master/src/BaselineOfPolyMath/BaselineOfPolyMath.class.st

is that right?

**Comment by SergeStinckwich** [comment]
No enough, replace two lines : 

```Smalltalk
package: 'Math-Quaternion' with: [ spec requires: #('Math-Complex') ];
package: 'Math-QuaternionExtensions' with: [ spec requires: #('Math-DHB-Numerical' 'Math-Quaternion' 'Math-Polynomials') ];
```

with 

```Smalltalk
package: 'Math-Quaternion' with: [ spec requires: #('Math-Complex' 'Math-DHB-Numerical' 'Math-Polynomials') ];
```

**Comment by SergeStinckwich** [comment]
ok I merge your changes on master. Next time you should do a PR on development branch. Look at the contributing guide here: https://github.com/PolyMathOrg/PolyMath/blob/development/CONTRIBUTING.md

**Pull request merged**
