### PR TITLE
Tests failing on pharo 10

### PR DESCRIPTION
**Pull request by olekscode**
Fixed 9 tests that were failing on Pharo 10

### CODE REVIEW

**Review by hemalvarambhia — APPROVED** [review]
Lost some test coverage but how well would any tests protect us from regression?

**Comment by olekscode** [comment]
I don't understand how there could be a loss of coverage... I didn't add any methods and didn't remove any tests.
I also didn't remove any calls to PolyMath methods

So it seems like a false alarm

**Comment by hemalvarambhia** [comment]
Possibly. Merge at your leisure.

**Comment by SergeStinckwich** [comment]
Thank you Oleks!

**Pull request merged**
