### PR TITLE
Convert Configuration to Baseline

### PR DESCRIPTION
**Pull request by jecisc**
Convert configuration to baseline.

Fixes https://github.com/PolyMathOrg/PolyMath/issues/46

### CODE REVIEW

**Comment by jecisc** [comment]
This will only work after the migration.

**Comment by jecisc** [comment]
It uses Tonel format. Is that what you wanted?

**Comment by SergeStinckwich** [comment]
Yes Tonel is better :-)

**Comment by SergeStinckwich** [comment]
We have some tests failing at the moment, nothing to worry :-)

**Comment by jecisc** [comment]
I just did a dummy convertion. If there is things to change I'll do it.

**Pull request merged**
